import { createStore } from 'vuex'

export default createStore({
  state: {
    cards: [
      {
        name: "abomination",
        description: "Глупый сброд! Вы ниже меня!",
        cost: 5,
        power: 9,
        pool: 0, // 0 -- стартовый пул, 1 -- уровни 1-14, 2- первый пул, 3 -- второй пул, 4 -- третий пул.
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: true,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "adam-warlock",
        description: "Если в конце хода вы выигрываете в этой локации, вы берете карту.",
        cost: 2,
        power: 0,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: true,
        discard: false,
        release: true
      },
      {
        name: "aero",
        description: "При раскрытии: Перемещает в эту локацию карты, сыгранные противником на этом ходу.",
        cost: 5,
        power: 8,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "agatha-harkness",
        description: "Начинает игру в руке и играет карты за вас.",
        cost: 6,
        power: 14,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "agent-13",
        description: "При раскрытии: Вы кладете в руку случайную карту.",
        cost: 1,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "america-chavez",
        description: "Вы можете взять эту карту только на 6 ходу, и не раньше.",
        cost: 6,
        power: 9,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "angel",
        description: "Когда какая-либо карта уничтожается, вылетает из колоды и занимает ее место.",
        cost: 1,
        power: 2,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: true,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "angela",
        description: "Когда вы играете карту в этой локации, получает +2 силы",
        cost: 2,
        power: 1,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "ant-man",
        description: "Продолжительный эффект: Имеет +3 силы, если в этой локации 4 карты.",
        cost: 1,
        power: 1,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "apocalypse",
        description: "При сбрасывании: Возвращается в руку с +4 силы.",
        cost: 6,
        power: 8,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: true,
        release: true
      },
      {
        name: "armor",
        description: "Продолжительный эффект: Карты в этой локации нельзя уничтожить.",
        cost: 2,
        power: 3,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "arnim-zola",
        description: "При раскрытии: Уничтожает случайную карту в этой локации и призывает ее копии в другие локации.",
        cost: 6,
        power: 0,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: true,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "baron-mordo",
        description: "При раскрытии: Противник берет карту. Ее стоимость становится равна 6.",
        cost: 2,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "beast",
        description: "При раскрытии: Возвращает карты из этой локации в вашу руку. Они стоят на 1 меньше.",
        cost: 2,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "bishop",
        description: "Когда вы разыгрываете карту, получает +1 силы.",
        cost: 3,
        power: 1,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "black-bolt",
        description: "При раскрытии: Противник сбрасывает карту с наименьшей стоимостью из своей руки.",
        cost: 5,
        power: 8,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: true,
        release: true
      },
      {
        name: "black-cat",
        description: "Если в конце хода эта карта находится в руке, вы ее сбрасываете.",
        cost: 3,
        power: 6,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: true,
        release: true
      },
      {
        name: "black-panther",
        description: "При раскрытии: Удваивает свою силу.",
        cost: 5,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "black-widow",
        description: "При раскрытии: Противник получает 'Укус вдовы' в свою руку.",
        cost: 2,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "blade",
        description: "При раскрытии: Вы сбрасываете случайную карту из руки.",
        cost: 1,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: true,
        release: true
      },
      {
        name: "blue-marvel",
        description: "Продолжительный эффект: Все другие карты имеют +1 силы.",
        cost: 5,
        power: 3,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "brood",
        description: "При раскрытии: Призывает 2 выводка с такой же силой.",
        cost: 3,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "bucky-barnes",
        description: "При уничтожении: Добавляет 'Зимнего солдата' с силой 6 в эту локацию.",
        cost: 2,
        power: 1,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: true,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "cable",
        description: "При раскрытии: Вы кладете в руку нижнюю карту колоды противника.",
        cost: 2,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "captain-america",
        description: "Продолжительный эффект: Другие карты в этой локации имеют +1 силы.",
        cost: 3,
        power: 3,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "carnage",
        description: "При раскрытии: Уничтожает все карты в этой локации и получает +2 к силе за каждую уничтоженную.",
        cost: 2,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: true,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "cerebro",
        description: "Продолжительный эффект: Ваши карты с наибольшей силой имеют +2 силы.",
        cost: 3,
        power: 0,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "cloak",
        description: "При раскрытии: На следующем ходу в эту локацию можно перемещать карты.",
        cost: 2,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "colleen-wing",
        description: "При раскрытии: Вы сбрасываете карту с наименьшей стоимостью из своей руки.",
        cost: 2,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: true,
        release: true
      },
      {
        name: "colossus",
        description: "Продолжительный эффект: Эту карту нельзя переместить, уничтожить и изменить ее силу.",
        cost: 2,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "cosmo",
        description: "Продолжительный эффект: В этой локации не срабатывают эффекты 'При раскрытии'.",
        cost: 3,
        power: 3,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "crossbones",
        description: "Эту карту можно играть только в локации, где вы выигрываете.",
        cost: 4,
        power: 8,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "crystal",
        description: "При раскрытии: Если эта локация средняя, вы замешиваете карты из своей руки в колоду и берете 3 карты.",
        cost: 4,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: true,
        discard: false,
        release: true
      },
      {
        name: "cyclops",
        description: "Вперед, Люди икс!",
        cost: 3,
        power: 4,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: true,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "dagger",
        description: "При перемещении получает +2 к силе за каждую карту противника в этой локации.",
        cost: 2,
        power: 1,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "daredevil",
        description: "На 5 ходу вы можете видеть ход противника, прежде чем сделать свой.",
        cost: 2,
        power: 2,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "deadpool",
        description: "При уничтожении: Удваивает свою силу и возвращается в вашу руку.",
        cost: 1,
        power: 1,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: true,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "death",
        description: "Стоит на 1 меньше за каждую уничтоженную карту.",
        cost: 9,
        power: 12,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: true,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "deathlok",
        description: "При раскрытии: Уничтожает все ваши карты в этой локации.",
        cost: 3,
        power: 5,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: true,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "debrii",
        description: "При раскрытии: Добавляет 'камень' в каждую другую локацию.",
        cost: 3,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "destroyer",
        description: "При раскрытии: Уничтожает все ваши карты.",
        cost: 6,
        power: 16,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: true,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "devil-dinosaur",
        description: "Продолжительный эффект: Имеет +2 силы за каждую карту в вашей руке.",
        cost: 5,
        power: 3,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "doctor-doom",
        description: "При раскрытии: Добавляет на вашу сторону 'думбота' с силой 5 в каждую локацию.",
        cost: 6,
        power: 5,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "doctor-octopus",
        description: "При раскрытии: Вытягивает все карты из руки противника в эту локацию.",
        cost: 5,
        power: 10,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "doctor-strange",
        description: "При раскрытии: Перемещает в эту локацию карты с наибольшей силой.",
        cost: 3,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "domino",
        description: "Вы можете взять эту карту только на 2 ходу, и не раньше.",
        cost: 2,
        power: 3,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "dracula",
        description: "В конце матча вы сбрасываете карты из своей руки. Получает силу сброшенной карты.",
        cost: 4,
        power: 0,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: true,
        release: true
      },
      {
        name: "drax",
        description: "При раскрытии: Если на этом ходу противник разыграл карту в этой локации, получает +4 силы.",
        cost: 4,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "ebony-maw",
        description: "Вы не можете разыграть эту карту после 3го хода. Продолжительный эффект: вы не можете играть карты в этой локации",
        cost: 1,
        power: 7,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "electro",
        description: "При раскрытии: Увеличивает вашу максимальную энергию на 1. Продолжительный эффект: вы можете играть только 1 карту в ход",
        cost: 3,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "elektra",
        description: "При раскрытии: Уничтожает карту противника со стоимостью 1 в этой локации.",
        cost: 1,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: true,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "enchantress",
        description: "При раскрытии: Удаляет все 'Продолжительные эффекты' у карт в этой локации.",
        cost: 4,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "falcon",
        description: "При раскрытии: Возвращает в вашу руку все ваши карты со стоимостью 1.",
        cost: 2,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "forge",
        description: "При раскрытии: Следующая разыгранная вами карта получит +2 к силе.",
        cost: 2,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "gambit",
        description: "При раскрытии: Вы сбрасываете случайную карту из своей руки. Уничтожает случайную карту противника.",
        cost: 3,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: true,
        noAbility: false,
        draw: false,
        discard: true,
        release: true
      },
      {
        name: "gamora",
        description: "При раскрытии: Если на этом ходу противник разыграл карту в этой локации, получает +5 силы.",
        cost: 5,
        power: 7,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "ghost-rider",
        description: "При раскрытии: Возвращает одну из сброшенных карт в эту локацию.",
        cost: 4,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: true,
        release: true
      },
      {
        name: "giganto",
        description: "Эту карту можно играть только в левую локацию.",
        cost: 6,
        power: 14,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "goose",
        description: "Продолжительный эффект: В этой локации нельзя играть карты стоимостью 4, 5 и 6.",
        cost: 2,
        power: 2,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "green-goblin",
        description: "При раскрытии: Противник получает контроль над этой картой.",
        cost: 3,
        power: -3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "groot",
        description: "При раскрытии: Если на этом ходу противник разыграл карту в этой локации, получает +3 силы.",
        cost: 3,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "hawkeye",
        description: "При раскрытии: Получает +2 к силе, если вы разыграете карту в этой локации на следующем ходу.",
        cost: 1,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "hazmat",
        description: "При раскрытии: Снижает силу всех других карт на 1.",
        cost: 2,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "heimdall",
        description: "При раскрытии: Перемещает все карты на локацию вправо.",
        cost: 6,
        power: 8,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "hela",
        description: "При раскрытии: Вы разыгрываете все сброшенные вами карты в случайные локации.",
        cost: 6,
        power: 6,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: true,
        release: true
      },
      {
        name: "hellcow",
        description: "При раскрытии: Вы сбрасываете 2 случайные карты из руки.",
        cost: 4,
        power: 6,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: true,
        release: true
      },
      {
        name: "hobgoblin",
        description: "При раскрытии: Противник получает контроль над этой картой.",
        cost: 5,
        power: -8,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "hulk-buster",
        description: "При раскрытии: Объединяется со случайной картой в этой локации.",
        cost: 3,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "hulk",
        description: "ХАЛК КРУШИТЬ!",
        cost: 6,
        power: 12,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: true,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "human-torch",
        description: "При перемещении удваивает свою силу.",
        cost: 1,
        power: 2,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "iceman",
        description: "При раскрытии: Увеличивает стоимость случайной карты в руке противника.(Максимум 6)",
        cost: 1,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "invisible-woman",
        description: "Продолжительный эффект: Сыгранные в этой локации карты раскроются в конце матча.",
        cost: 2,
        power: 2,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "iron-fist",
        description: "При раскрытии: Ваша следующая карта переместится на локацию слева.",
        cost: 1,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "iron-man",
        description: "Продолжительный эффект: Удваивает силу этой локации.",
        cost: 5,
        power: 0,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "ironheart",
        description: "При раскрытии: Дает трем другим вашим картам +2 к силе.",
        cost: 3,
        power: 0,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "jane-foster-mighty-thor",
        description: "При раскрытии: Вы берете все карты со стоимостью 0 из колоды.",
        cost: 5,
        power: 8,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: true,
        discard: false,
        release: true
      },
      {
        name: "jessica-jones",
        description: "При раскрытии: Если на следующем ходу вы не разыграли карту в этой локации, получает +4 к силе.",
        cost: 4,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "jubilee",
        description: "При раскрытии: Вы разыгрываете карту из вашей колоды в эту локацию.",
        cost: 4,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "juggernaut",
        description: "При раскрытии: Перемещает в другие локации вражеские карты, разыгранные в этой локации на этом ходу.",
        cost: 3,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "ka-zar",
        description: "Продолжительный эффект: Все ваши карты со стоимостью 1 имеют +1 силы.",
        cost: 4,
        power: 4,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "killmonger",
        description: "При раскрытии: Уничтожает все карты со стоимостью 1.",
        cost: 3,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: true,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "kingpin",
        description: "Продолжительный эффект: На 6 ходу перемещенные в эту локацию карты уничтожаются.",
        cost: 3,
        power: 4,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: true,
        destroy: true,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "klaw",
        description: "Продолжительный эффект: Локация справа имеет +6 силы.",
        cost: 5,
        power: 4,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "korg",
        description: "При раскрытии: Замешивает камень в колоду противника.",
        cost: 1,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "kraven",
        description: "Эта карта получает +2 к силе каждый раз, когда в эту локацию перемещается карта.",
        cost: 2,
        power: 2,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "lady-sif",
        description: "При раскрытии: Вы сбрасываете карту с наибольшей стоимостью из своей руки.",
        cost: 3,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: true,
        release: true
      },
      {
        name: "leader",
        description: "При раскрытии: Копирует на вашу сторону все сыгранные противником на этом ходу карты.",
        cost: 6,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "leech",
        description: "При раскрытии: Удаляет все способности у карт в руке противника.",
        cost: 5,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "lizard",
        description: "Продолжительный эффект: Имеет -3 силы, если у противника 4 карты в этой локации.",
        cost: 2,
        power: 5,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "lockjaw",
        description: "Когда вы разыгрываете карту в этой локации, заменяет ее на случайную карту из вашей колоды.",
        cost: 3,
        power: 2,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "magik",
        description: "Вы не можете играть эту карту на 6м ходу. При раскрытии: превращает эту локацию в Limbo",
        cost: 5,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "magneto",
        description: "При раскрытии: Перемещает в эту локацию карты противника со стоимостью 3 и 4.",
        cost: 6,
        power: 12,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "mantis",
        description: "При раскрытии: Если противник сыграл карту в этой локации на этом ходу, вы берете карту из его колоды.",
        cost: 1,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "maximus",
        description: "При раскрытии: Противник берет 2 карты.",
        cost: 3,
        power: 7,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: true,
        discard: false,
        release: true
      },
      {
        name: "medusa",
        description: "При раскрытии: Получает +2 к силе, если это средняя локация.",
        cost: 2,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "miles-morales",
        description: "Стоит 1, если карта перемещалась на прошлом ходу.",
        cost: 4,
        power: 5,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "mister-fantastic",
        description: "Продолжительный эффект: Соседние локации имеют +2 силы.",
        cost: 3,
        power: 2,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "mister-negative",
        description: "При раскрытии: Меняет местами стоимость и силу карты в вашей колоде.",
        cost: 4,
        power: -1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "mister-sinister",
        description: "При раскрытии: Призывает клона с такой же силой.",
        cost: 2,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "misty-knight",
        description: "Мы должны спасти этот город.",
        cost: 1,
        power: 2,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: true,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "mojo",
        description: "Продолжительный эффект: Имеет +6 силы, если у обоих игроков в этой локации 4 карты.",
        cost: 2,
        power: 2,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "moon-girl",
        description: "При раскрытии: Копирует карты в вашей руке.",
        cost: 4,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "moon-knight",
        description: "При раскрытии: Оба игрока сбрасывают случайную карту из своей руки.",
        cost: 3,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: true,
        release: true
      },
      {
        name: "morbius",
        description: "Продолжительный эффект: Имеет +2 силы за каждую сброшенную вами карту в этом матче.",
        cost: 2,
        power: 0,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: true,
        release: true
      },
      {
        name: "morph",
        description: "При раскрытии: Превращается в случайную карту из руки противника.",
        cost: 3,
        power: 0,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "multiple-man",
        description: "При перемещении создает свою копию в бывшей локации.",
        cost: 2,
        power: 3,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "mysterio",
        description: "Маскируется под иллюзию, создавая иллюзии с силой 0 в других локациях. Раскроется в конце хода.",
        cost: 2,
        power: 5,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "mystique",
        description: "При раскрытии: Если ваша последняя сыгранная карта имела 'Продолжительный эффект', копирует его.",
        cost: 5,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "nakia",
        description: "При раскрытии: Дает +2 к силе двум вашим левым картам в руке.",
        cost: 3,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "namor",
        description: "Продолжительный эффект: Имеет +5 силы, сли это единственная ваша карта в этой локации.",
        cost: 4,
        power: 5,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "nick-fury",
        description: "При раскрытии: Добавляет в вашу руку три карты со стоимостью 6.",
        cost: 5,
        power: 7,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "nightcrawler",
        description: "Эту карту можно переместить один раз.",
        cost: 1,
        power: 2,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "nova",
        description: "При уничтожении другие ваши карты получают +1 к силе.",
        cost: 1,
        power: 2,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: true,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "odin",
        description: "При раскрытии: Активирует ваши эффекты 'При раскрытии' у карт в этой локации.",
        cost: 5,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "okoye",
        description: "При раскрытии: Дает +1 к силе всем картам в вашей колоде.",
        cost: 2,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "omega-red",
        description: "Продолжительный эффект: Другие локации имеют +4 силы, если в этой локации вы опережаете противника на 10 силы.",
        cost: 4,
        power: 5,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "onslaught",
        description: "Продолжительный эффект: Удваивает 'Продолжительный эффект' у других карт в этой локации.",
        cost: 6,
        power: 7,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "patriot",
        description: "Продолжительный эффект: Все ваши карты без способностей имеют +2 силы.",
        cost: 3,
        power: 1,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "polaris",
        description: "При раскрытии: Перемещает карту противника со стоимостью 1 или 2 в эту локацию.",
        cost: 3,
        power: 5,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "professor-x",
        description: "Продолжительный эффект: Блокирует эту локацию.(Карты нельзя добавить, уничтожить, переместить и так далее.)",
        cost: 5,
        power: 3,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "psylocke",
        description: "При раскрытии: На следующем ходу вы получаете +1 к энергии.",
        cost: 2,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "punisher",
        description: "Продолжительный эффект: Имеет +1 силы за каждую карту противника в этой локации.",
        cost: 5,
        power: 3,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "quake",
        description: "При раскрытии: Если это средняя локация, все локации меняются местами.",
        cost: 2,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "quicksilver",
        description: "Начинает игру в стартовой руке.",
        cost: 1,
        power: 2,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "quinjet",
        description: "Продолжительный эффект: Карты, которых не было в вашей колоде, стоят на 1 меньше.",
        cost: 2,
        power: 3,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "red-skull",
        description: "Продолжительный эффект: Карты противника в этой локации имеют +2 силы.",
        cost: 5,
        power: 15,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "rescue",
        description: "При раскрытии: Получит +5 к силе, если на следующем ходу вы разыграете карту в этой локации.",
        cost: 4,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "rhino",
        description: "При раскрытии: Превращает локацию в 'Руины'.",
        cost: 3,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "rocket-racoon",
        description: "При раскрытии: Если на этом ходу противник разыграл карту в этой локации, получает +2 к силе.",
        cost: 1,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "rockslide",
        description: "При раскрытии: Замешивает 2 камня в колоду противника.",
        cost: 4,
        power: 6,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "rogue",
        description: "При раскрытии: Крадет 'Продолжительный эффект' у случайной карты противника в этой локации.",
        cost: 3,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "ronan-the-accuser",
        description: "Продолжительный эффект: Имеет +2 к силе за каждую карту в вашей руке.",
        cost: 5,
        power: 3,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "sabretooth",
        description: "При уничтожении возвращается в руку со стоимостью 0.",
        cost: 3,
        power: 4,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: true,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "sandman",
        description: "Продолжительный эффект: Игроки могут играть только одну карту в ход.",
        cost: 4,
        power: 1,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "scarlet-witch",
        description: "При раскрытии: Превращает эту локацию в случайную другую.",
        cost: 2,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "scorpion",
        description: "При раскрытии: Снижает силу карт в руке противника на 1.",
        cost: 2,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "sentinel",
        description: "При раскрытии: Кладет в вашу руку 'Sentinel'.",
        cost: 2,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "sera",
        description: "Продолжительный эффект: Ваши карты стоят на 1 меньше.(Минимум 1).",
        cost: 5,
        power: 5,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "shang-chi",
        description: "При раскрытии: Уничтожает карты противника с силой 9 и больше в этой локации.",
        cost: 4,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: true,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "shocker",
        description: "Я взорву тебя!",
        cost: 2,
        power: 3,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: true,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "spectrum",
        description: "При раскрытии: Все ваши карты с 'Продолжительным эффектом' получают +2 к силе.",
        cost: 6,
        power: 5,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "spider-man",
        description: "При раскрытии: Ваш противник не может играть карты в этой локации на следующем ходу.",
        cost: 4,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "spider-woman",
        description: "При раскрытии: Снижает силу карту противника в этой локации на 1.",
        cost: 5,
        power: 7,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "squirrel-girl",
        description: "При раскрытии: Добавляет белочку с силой 1 в другие локации.",
        cost: 1,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "star-lord",
        description: "При раскрытии: Если на этом ходу противник разыграл карту в этой локации, получает +3 к силе. ",
        cost: 2,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "storm",
        description: "При раскрытии: Затопляет эту локацию. Следующий ход последний, когда в ней можно играть карты.",
        cost: 3,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "strong-guy",
        description: "Продолжительный эффект: Имеет +6 силы, если ваша рука пуста.",
        cost: 4,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "sunspot",
        description: "В конце хода получает +1 к силе за каждую неизрасходованную энергию.",
        cost: 1,
        power: 1,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "swarm",
        description: "При сбрасывании добавляет в вашу руку две свои копии. Они стоят 0.",
        cost: 2,
        power: 3,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: true,
        release: true
      },
      {
        name: "sword-master",
        description: "При раскрытии: Вы сбрасываете случайную карту из своей руки.",
        cost: 3,
        power: 6,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: true,
        release: true
      },
      {
        name: "taskmaster",
        description: "При раскрытии: Получает силу последней сыгранной вами карты.",
        cost: 5,
        power: 0,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "thanos",
        description: "При раскрытии: Замешивает в вашу колоду камни бесконечности.",
        cost: 6,
        power: 8,
        pool: 6,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "the-collector",
        description: "Получает +1 к силе каждый раз, когда в вашу руку попадает карта, которой не было в колоде.",
        cost: 2,
        power: 1,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "the-hood",
        description: "При раскрытии: Добавляет в вашу руку демона с силой 6.",
        cost: 1,
        power: -2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "the-infinaut",
        description: "Эту карту нельзя разыграть, если вы играли карту на прошлом ходу.",
        cost: 6,
        power: 20,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "the-thing",
        description: "Пора крушить!",
        cost: 4,
        power: 6,
        pool: 0,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: true,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "thor",
        description: "При раскрытии: Замешивает в вашу колоду 'Мъёльнир'.",
        cost: 3,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "typhoid-mary",
        description: "Продолжительный эффект: Все ваши другие карты имеют -1 силы.",
        cost: 4,
        power: 10,
        pool: 4,
        onReveal: false,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "uatu",
        description: "Вы можете видеть нераскрытые локации.",
        cost: 1,
        power: 2,
        pool: 2,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "ultron",
        description: "При раскрытии: Заполняет вашу сторону дронами с силой 1 в других локациях.",
        cost: 6,
        power: 8,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "venom",
        description: "При раскрытии: Уничтожает ваши другие карты в этой локации и получает их суммарную силу.",
        cost: 3,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: true,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "viper",
        description: "При раскрытии: Противник получает контроль над другой вашей случайной картой в этой локации.",
        cost: 2,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "vision",
        description: "Можно перемещать каждый ход.",
        cost: 5,
        power: 7,
        pool: 3,
        onReveal: false,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "vulture",
        description: "При перемещении получает +5 к силе.",
        cost: 3,
        power: 3,
        pool: 2,
        onReveal: false,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "warpath",
        description: "Продолжительный эффект: Имеет +4 силы, если одна из ваших локаций пуста.",
        cost: 4,
        power: 5,
        pool: 3,
        onReveal: false,
        ongoing: true,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "wasp",
        description: "Моя тайная сила в том, что я добиваюсь цели.",
        cost: 0,
        power: 1,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: true,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "wave",
        description: "При раскрытии: На следующем ходу карты в руках обоих игроков стоят 4.",
        cost: 3,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "white-queen",
        description: "При раскрытии: Добавляет в вашу руку карту из руки противника с наибольшей стоимостью.",
        cost: 4,
        power: 6,
        pool: 2,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "white-tiger",
        description: "При раскрытии: Добавляет тигра с силой 7 на вашу сторону в другую локацию.",
        cost: 5,
        power: 1,
        pool: 2,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "wolfsbane",
        description: "При раскрытии: Получает +2 к силе за каждую вашу другую карту в этой локации.",
        cost: 3,
        power: 1,
        pool: 2,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "wolverine",
        description: "При уничтожении и сбрасывании прыгает на вашу сторону в случайной локации.",
        cost: 2,
        power: 3,
        pool: 2,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: true,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "wong",
        description: "Продолжительный эффект: Ваши эффекты 'При раскрытии' в этой локации срабатывают дважды.",
        cost: 4,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: true,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "yellowjacket",
        description: "При раскрытии: Снижает силу других ваших карт в этой локации на 1.",
        cost: 0,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "yondu",
        description: "При раскрытии: Удаляет вернхнюю карту колоды противника.",
        cost: 1,
        power: 2,
        pool: 2,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
      {
        name: "zero",
        description: "При раскрытии: Удаляет способность следующей вашей карты, которую вы разыграете.",
        cost: 1,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false,
        release: true
      },
        {
          name: "absorbing-man",
          description: "При раскрытии: Если последняя сыгранная вами карта имела эффект 'При раскрытии', эта карта копирует его.",
          cost: 4,
          power: 3,
          pool: 5,
          onReveal: true,
          ongoing: false,
          move: false,
          destroy: false,
          noAbility: false,
          draw: false,
          discard: false,
          release: false
        },
        {
          name: "galactus",
          description: "При раскрытии: Если это ваша единственная карта в этой локации, уничтожает остальные локации.",
          cost: 6,
          power: 3,
          pool: 6,
          onReveal: true,
          ongoing: false,
          move: true,
          destroy: false,
          noAbility: false,
          draw: false,
          discard: false,
          release: false
        },
      ],
    filteredCards: [],
    locations: [
      {
        name: 'asgard',
        description: 'После 4го хода тыры пыры очень классно'
      },
      {
        name: 'daily-bugle',
        description: 'После 4го хода тыры пыры очень классно'
      }
    ]
  },
  getters: {
    getCards (state) {
      return state.cards;
    },
    getFilteredCards (state) {
      return state.filteredCards;
    },
    getLocations (state) {
      return state.locations;
    }
  },
  mutations: {
    setFilteredCards (state, payload) {
      state.filteredCards = payload;
    },
  },
  actions: {
  },
  modules: {
  }
})
