import { createStore } from 'vuex'

export default createStore({
  state: {
    cards: {
      released: [
      {
        name: "abomination",
        description: "Глупый сброд! Вы ниже меня!",
        cost: 5,
        power: 9,
        pool: 0, // 0 -- стартовый пул, 1 -- уровни 1-14, 2- первый пул, 3 -- второй пул, 4 -- третий пул.
        onReveal: false, // true, false
        ongoing: false, // true, false
        move: false, // true, false
        destroy: false, // true, false
        noAbility: true, // true, false в
        draw: false, // true, false
        discard: false
      },
      {
        name: "adam-warlock",
        description: "Если в конце хода вы выигрываете в этой локации, вы берете карту.",
        cost: 2,
        power: 0,
        pool: 4,
        onReveal: false,
        ongoing: false,
        move: false,
        destroy: false,
        noAbility: false,
        draw: true,
        discard: false
      },
      {
        name: "aero",
        description: "При раскрытии: Перемещает в эту локацию карты, сыгранные противником на этом ходу.",
        cost: 5,
        power: 8,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "agatha-harkness",
        description: "Начинает игру в руке и играет карты за вас.",
        cost: 6,
        power: 14,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "agent-13",
        description: "При раскрытии: Вы кладете в руку случайную карту.",
        cost: 1,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "america-chavez",
        description: "Вы можете взять эту карту только на 6 ходу, и не раньше.",
        cost: 6,
        power: 9,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "angel",
        description: "Когда какая-либо карта уничтожается, вылетает из колоды и занимает ее место.",
        cost: 1,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "angela",
        description: "Когда вы играете карту в этой локации, получает +2 силы",
        cost: 2,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "ant-man",
        description: "Продолжительный эффект: Имеет +3 силы, если в этой локации 4 карты.",
        cost: 1,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "apocalypse",
        description: "При сбрасывании: Возвращается в руку с +4 силы.",
        cost: 6,
        power: 8,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "armor",
        description: "Продолжительный эффект: Карты в этой локации нельзя уничтожить.",
        cost: 2,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "arnim-zola",
        description: "При раскрытии: Уничтожает случайную карту в этой локации и призывает ее копии в другие локации.",
        cost: 6,
        power: 0,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "baron-mordo",
        description: "При раскрытии: Противник берет карту. Ее стоимость становится равна 6.",
        cost: 2,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "beast",
        description: "При раскрытии: Возвращает карты из этой локации в вашу руку. Они стоят на 1 меньше.",
        cost: 2,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "bishop",
        description: "Когда вы разыгрываете карту, получает +1 силы.",
        cost: 3,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "black-bolt",
        description: "При раскрытии: Противник сбрасывает карту с наименьшей стоимостью из своей руки.",
        cost: 5,
        power: 8,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "black-cat",
        description: "Если в конце хода эта карта находится в руке, вы ее сбрасываете.",
        cost: 3,
        power: 6,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "black-panther",
        description: "При раскрытии: Удваивает свою силу.",
        cost: 5,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "black-widow",
        description: "При раскрытии: Противник получает 'Укус вдовы' в свою руку.",
        cost: 2,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "blade",
        description: "При раскрытии: Вы сбрасываете случайную карту из руки.",
        cost: 1,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "blue-marvel",
        description: "Продолжительный эффект: Все другие карты имеют +1 силы.",
        cost: 5,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "brood",
        description: "При раскрытии: Призывает 2 выводка с такой же силой.",
        cost: 3,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "bucky-barnes",
        description: "При уничтожении: Добавляет 'Зимнего солдата' с силой 6 в эту локацию.",
        cost: 2,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "cable",
        description: "При раскрытии: Вы кладете в руку нижнюю карту колоды противника.",
        cost: 2,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "captain-america",
        description: "Продолжительный эффект: Другие карты в этой локации имеют +1 силы.",
        cost: 3,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "carnage",
        description: "При раскрытии: Уничтожает все карты в этой локации и получает +2 к силе за каждую уничтоженную.",
        cost: 2,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "cerebro",
        description: "Продолжительный эффект: Ваши карты с наибольшей силой имеют +2 силы.",
        cost: 3,
        power: 0,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "cloak",
        description: "При раскрытии: На следующем ходу в эту локацию можно перемещать карты.",
        cost: 2,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "colleen-wing",
        description: "При раскрытии: Вы сбрасываете карту с наименьшей стоимостью из своей руки.",
        cost: 2,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "colossus",
        description: "Продолжительный эффект: Эту карту нельзя переместить, уничтожить и изменить ее силу.",
        cost: 2,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "cosmo",
        description: "Продолжительный эффект: В этой локации не срабатывают эффекты 'При раскрытии'.",
        cost: 3,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "crossbones",
        description: "Эту карту можно играть только в локации, где вы выигрываете.",
        cost: 4,
        power: 8,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "crystal",
        description: "При раскрытии: Если эта локация средняя, вы замешиваете карты из своей руки в колоду и берете 3 карты.",
        cost: 4,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "cyclops",
        description: "Вперед, Люди икс!",
        cost: 3,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "dagger",
        description: "При перемещении получает +2 к силе за каждую карту противника в этой локации.",
        cost: 2,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "daredevil",
        description: "На 5 ходу вы можете видеть ход противника, прежде чем сделать свой.",
        cost: 2,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "deadpool",
        description: "При уничтожении: Удваивает свою силу и возвращается в вашу руку.",
        cost: 1,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "death",
        description: "Стоит на 1 меньше за каждую уничтоженную карту.",
        cost: 9,
        power: 12,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "deathlok",
        description: "При раскрытии: Уничтожает все ваши карты в этой локации.",
        cost: 3,
        power: 5,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "debrii",
        description: "При раскрытии: Добавляет 'камень' в каждую другую локацию.",
        cost: 3,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "destroyer",
        description: "При раскрытии: Уничтожает все ваши карты.",
        cost: 6,
        power: 16,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "devil-dinosaur",
        description: "Продолжительный эффект: Имеет +2 силы за каждую карту в вашей руке.",
        cost: 5,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "doctor-doom",
        description: "При раскрытии: Добавляет на вашу сторону 'думбота' с силой 5 в каждую локацию.",
        cost: 6,
        power: 5,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "doctor-octopus",
        description: "При раскрытии: Вытягивает все карты из руки противника в эту локацию.",
        cost: 5,
        power: 10,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "doctor-strange",
        description: "При раскрытии: Перемещает в эту локацию карты с наибольшей силой.",
        cost: 3,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "domino",
        description: "Вы можете взять эту карту только на 2 ходу, и не раньше.",
        cost: 2,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "dracula",
        description: "В конце матча вы сбрасываете карты из своей руки. Получает силу сброшенной карты.",
        cost: 4,
        power: 0,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "drax",
        description: "При раскрытии: Если на этом ходу противник разыграл карту в этой локации, получает +4 силы.",
        cost: 4,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "ebony-maw",
        description: "Тест",
        cost: 1,
        power: 7,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "electro",
        description: "Tecт",
        cost: 3,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "elektra",
        description: "При раскрытии: Уничтожает карту противника со стоимостью 1 в этой локации.",
        cost: 1,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "enchantress",
        description: "При раскрытии: Удаляет все 'Продолжительные эффекты' у карт в этой локации.",
        cost: 4,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "falcon",
        description: "При раскрытии: Возвращает в вашу руку все ваши карты со стоимостью 1.",
        cost: 2,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "forge",
        description: "При раскрытии: Следующая разыгранная вами карта получит +2 к силе.",
        cost: 2,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "gambit",
        description: "При раскрытии: Вы сбрасываете случайную карту из своей руки. Уничтожает случайную карту противника.",
        cost: 3,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "gamora",
        description: "При раскрытии: Если на этом ходу противник разыграл карту в этой локации, получает +5 силы.",
        cost: 5,
        power: 7,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "ghost-rider",
        description: "При раскрытии: Возвращает одну из сброшенных карт в эту локацию.",
        cost: 4,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "giganto",
        description: "Эту карту можно играть только в левую локацию.",
        cost: 6,
        power: 14,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "goose",
        description: "Продолжительный эффект: В этой локации нельзя играть карты стоимостью 4, 5 и 6.",
        cost: 2,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "green-goblin",
        description: "При раскрытии: Противник получает контроль над этой картой.",
        cost: 3,
        power: -3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "groot",
        description: "При раскрытии: Если на этом ходу противник разыграл карту в этой локации, получает +3 силы.",
        cost: 3,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "hawkeye",
        description: "При раскрытии: Получает +2 к силе, если вы разыграете карту в этой локации на следующем ходу.",
        cost: 1,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "hazmat",
        description: "При раскрытии: Снижает силу всех других карт на 1.",
        cost: 2,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "heimdall",
        description: "При раскрытии: Перемещает все карты на локацию вправо.",
        cost: 6,
        power: 8,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "hela",
        description: "При раскрытии: Вы разыгрываете все сброшенные вами карты в случайные локации.",
        cost: 6,
        power: 6,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "hellcow",
        description: "При раскрытии: Вы сбрасываете 2 случайные карты из руки.",
        cost: 4,
        power: 6,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "hobgoblin",
        description: "При раскрытии: Противник получает контроль над этой картой.",
        cost: 5,
        power: -8,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "hulk-buster",
        description: "При раскрытии: Объединяется со случайной картой в этой локации.",
        cost: 3,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "hulk",
        description: "ХАЛК КРУШИТЬ!",
        cost: 6,
        power: 12,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "human-torch",
        description: "При перемещении удваивает свою силу.",
        cost: 1,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "iceman",
        description: "При раскрытии: Увеличивает стоимость случайной карты в руке противника.(Максимум 6)",
        cost: 1,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "invisible-woman",
        description: "Продолжительный эффект: Сыгранные в этой локации карты раскроются в конце матча.",
        cost: 2,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "iron-fist",
        description: "При раскрытии: Ваша следующая карта переместится на локацию слева.",
        cost: 1,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "iron-man",
        description: "Продолжительный эффект: Удваивает силу этой локации.",
        cost: 5,
        power: 0,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "ironheart",
        description: "При раскрытии: Дает трем другим вашим картам +2 к силе.",
        cost: 3,
        power: 0,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "jane-foster-mighty-thor",
        description: "При раскрытии: Вы берете все карты со стоимостью 0 из колоды.",
        cost: 5,
        power: 8,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "jessica-jones",
        description: "При раскрытии: Если на следующем ходу вы не разыграли карту в этой локации, получает +4 к силе.",
        cost: 4,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "jubilee",
        description: "При раскрытии: Вы разыгрываете карту из вашей колоды в эту локацию.",
        cost: 4,
        power: 1,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "juggernaut",
        description: "При раскрытии: Перемещает в другие локации вражеские карты, разыгранные в этой локации на этом ходу.",
        cost: 3,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "ka-zar",
        description: "Продолжительный эффект: Все ваши карты со стоимостью 1 имеют +1 силы.",
        cost: 4,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "killmonger",
        description: "При раскрытии: Уничтожает все карты со стоимостью 1.",
        cost: 3,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "kingpin",
        description: "Продолжительный эффект: На 6 ходу перемещенные в эту локацию карты уничтожаются.",
        cost: 3,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "klaw",
        description: "Продолжительный эффект: Локация справа имеет +6 силы.",
        cost: 5,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "korg",
        description: "При раскрытии: Замешивает камень в колоду противника.",
        cost: 1,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "kraven",
        description: "Эта карта получает +2 к силе каждый раз, когда в эту локацию перемещается карта.",
        cost: 2,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "lady-sif",
        description: "При раскрытии: Вы сбрасываете карту с наибольшей стоимостью из своей руки.",
        cost: 3,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "leader",
        description: "При раскрытии: Копирует на вашу сторону все сыгранные противником на этом ходу карты.",
        cost: 6,
        power: 4,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "leech",
        description: "При раскрытии: Удаляет все способности у карт в руке противника.",
        cost: 5,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "lizard",
        description: "Продолжительный эффект: Имеет -3 силы, если у противника 4 карты в этой локации.",
        cost: 2,
        power: 5,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "lockjaw",
        description: "Когда вы разыгрываете карту в этой локации, заменяет ее на случайную карту из вашей колоды.",
        cost: 3,
        power: 2,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
      {
        name: "magik",
        description: "Тест",
        cost: 5,
        power: 3,
        pool: 4,
        onReveal: true,
        ongoing: false,
        move: true,
        destroy: false,
        noAbility: false,
        draw: false,
        discard: false
      },
    ],
      unreleased: [
        {
          name: "absorbing-man",
          description: "On Reveal: If the last card you played has an On Reveal ability, this card copies it.",
          cost: 4,
          power: 3,
          pool: 4,
          onReveal: true,
          ongoing: false,
          move: true,
          destroy: false,
          noAbility: false,
          draw: false,
          discard: false
        },
        {
          name: "thanos",
          description: "Описание для таноса",
          cost: 6,
          power: 8,
          pool: 4,
          onReveal: true,
          ongoing: false,
          move: true,
          destroy: false,
          noAbility: false,
          draw: false,
          discard: false
        },
        {
          name: "galactus",
          description: "Описание для Галактуса",
          cost: 6,
          power: 3,
          pool: 4,
          onReveal: true,
          ongoing: false,
          move: true,
          destroy: false,
          noAbility: false,
          draw: false,
          discard: false
        },
      ]
    }
  },
  getters: {
    getCards (state) {
      return state.cards;
    }
  },
  mutations: {
  },
  actions: {
  },
  modules: {
  }
})
